package aiexecution

import (
	"crypto/rand"
	"encoding/binary"
	"encoding/hex"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
)

const RuntimeProjection = "managed-runtime-v1"

// RuntimeExpectation stores digests generated by the gateway's own read-only
// admission-config-digests command. Maestro never guesses its normalization.
type RuntimeExpectation struct {
	ManagementKeyEnv       string    `json:"management_key_env"`
	ProjectionVersion      string    `json:"projection_version"`
	ProcessInstanceID      string    `json:"process_instance_id"`
	StartedAt              time.Time `json:"started_at"`
	BuildVersion           string    `json:"build_version"`
	GitCommit              string    `json:"git_commit"`
	ManagedAdmissionSHA256 string    `json:"managed_admission_sha256"`
	ExecutionConfigSHA256  string    `json:"execution_config_sha256"`
}

type runtimeReceipt struct {
	ObservationScope  string    `json:"observation_scope"`
	SchemaVersion     int       `json:"schema_version"`
	ProjectionVersion string    `json:"projection_version"`
	ProcessInstanceID string    `json:"process_instance_id"`
	StartedAt         time.Time `json:"started_at"`
	ObservedAt        time.Time `json:"observed_at"`
	RequestNonce      string    `json:"request_nonce"`
	Build             struct {
		Version   string `json:"version"`
		GitCommit string `json:"git_commit"`
	} `json:"build"`
	ConfigApplyComplete bool `json:"config_apply_complete"`
	ManagedAdmission    struct {
		Enabled         bool   `json:"enabled"`
		BuiltinOnly     bool   `json:"builtin_only"`
		CallerScopeHash string `json:"caller_scope_hash"`
		PolicyVersion   int64  `json:"policy_version"`
		StartupSHA256   string `json:"startup_sha256"`
		CurrentSHA256   string `json:"current_sha256"`
		Drift           bool   `json:"drift"`
	} `json:"managed_admission"`
	ExecutionConfig struct {
		StartupSHA256 string `json:"startup_sha256"`
		CurrentSHA256 string `json:"current_sha256"`
		Drift         bool   `json:"drift"`
	} `json:"execution_config"`
}

func observeRuntime(m Manifest, callerScopeHash string) error {
	e := m.Runtime
	id, err := uuid.Parse(e.ProcessInstanceID)
	if err != nil || id.String() != e.ProcessInstanceID || e.ProjectionVersion != RuntimeProjection || e.StartedAt.IsZero() || e.BuildVersion == "" || e.GitCommit == "" || !validDigest(e.ManagedAdmissionSHA256) || !validDigest(e.ExecutionConfigSHA256) || !validDigest(callerScopeHash) {
		return Held("runtime_expectation_invalid")
	}
	u, err := url.Parse(m.GatewayURL)
	if err != nil || u.Scheme != "http" || u.User != nil || u.RawQuery != "" || u.Fragment != "" || u.Path != "" && u.Path != "/" {
		return Held("runtime_observation_route_unsupported")
	}
	ip := net.ParseIP(u.Hostname())
	port, err := strconv.Atoi(u.Port())
	if ip == nil || !ip.IsLoopback() || err != nil || port <= 0 || port > 65535 {
		return Held("runtime_observation_route_unsupported")
	}
	if err := inspectListener(m.Gateway.PID, ip, port); err != nil {
		return err
	}
	if e.ManagementKeyEnv == "" || strings.IndexFunc(e.ManagementKeyEnv, func(r rune) bool { return !(r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_') }) >= 0 {
		return Held("runtime_management_key_unavailable")
	}
	key := os.Getenv(e.ManagementKeyEnv)
	if key == "" {
		return Held("runtime_management_key_unavailable")
	}
	var random [16]byte
	if _, err := rand.Read(random[:]); err != nil {
		return Held("runtime_nonce_unavailable")
	}
	nonce := hex.EncodeToString(random[:])
	u.Path = "/v8/management/observability/admission/runtime"
	u.RawQuery = "request_nonce=" + nonce
	req, err := http.NewRequest(http.MethodGet, u.String(), nil)
	if err != nil {
		return Held("runtime_observation_unavailable")
	}
	req.Header.Set("Authorization", "Bearer "+key)
	// A fresh direct connection has no proxy, redirects, retries or reused
	// transport state. This request observes capability and cannot do inference.
	transport := &http.Transport{Proxy: nil, DisableKeepAlives: true, DialContext: (&net.Dialer{Timeout: 2 * time.Second}).DialContext}
	defer transport.CloseIdleConnections()
	client := &http.Client{Transport: transport, Timeout: 3 * time.Second, CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }}
	start := time.Now()
	response, err := client.Do(req)
	if err != nil {
		return Held("runtime_observation_unavailable")
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK || !strings.Contains(strings.ToLower(response.Header.Get("Cache-Control")), "no-store") {
		return Held("runtime_observation_rejected")
	}
	b, err := io.ReadAll(io.LimitReader(response.Body, (64<<10)+1))
	if err != nil || len(b) > 64<<10 {
		return Held("runtime_observation_invalid")
	}
	var receipt runtimeReceipt
	if DecodeStrict(b, &receipt) != nil {
		return Held("runtime_observation_invalid")
	}
	if receipt.ObservationScope != "configuration_only" || receipt.SchemaVersion != 1 || receipt.ProjectionVersion != e.ProjectionVersion || receipt.RequestNonce != nonce || receipt.ProcessInstanceID != e.ProcessInstanceID || !receipt.StartedAt.Equal(e.StartedAt) || receipt.Build.Version != e.BuildVersion || receipt.Build.GitCommit != e.GitCommit || receipt.ObservedAt.Before(start.Add(-time.Second)) || receipt.ObservedAt.After(time.Now().Add(time.Second)) {
		return Held("runtime_observation_binding_mismatch")
	}
	admission := receipt.ManagedAdmission
	execution := receipt.ExecutionConfig
	if !receipt.ConfigApplyComplete || !admission.Enabled || !admission.BuiltinOnly || admission.Drift || execution.Drift || admission.CallerScopeHash != callerScopeHash || admission.PolicyVersion != m.PolicyVersion || admission.StartupSHA256 != e.ManagedAdmissionSHA256 || admission.CurrentSHA256 != e.ManagedAdmissionSHA256 || execution.StartupSHA256 != e.ExecutionConfigSHA256 || execution.CurrentSHA256 != e.ExecutionConfigSHA256 {
		return Held("runtime_config_drift")
	}
	return inspectListener(m.Gateway.PID, ip, port)
}

// Bind the loopback observation socket to the inspected gateway process. A
// matching JSON body from some other local server is not process evidence.
func inspectListener(pid int, ip net.IP, port int) error {
	root := "/proc/" + strconv.Itoa(pid)
	selfNS, err := os.Stat("/proc/self/ns/net")
	if err != nil {
		return Held("gateway_network_namespace_unobservable")
	}
	gatewayNS, err := os.Stat(root + "/ns/net")
	if err != nil || !os.SameFile(selfNS, gatewayNS) {
		return Held("gateway_network_namespace_mismatch")
	}
	fds, err := os.ReadDir(root + "/fd")
	if err != nil {
		return Held("gateway_listener_unobservable")
	}
	owned := map[string]bool{}
	for _, fd := range fds {
		link, err := os.Readlink(filepath.Join(root, "fd", fd.Name()))
		if err == nil && strings.HasPrefix(link, "socket:[") && strings.HasSuffix(link, "]") {
			owned[strings.TrimSuffix(strings.TrimPrefix(link, "socket:["), "]")] = true
		}
	}
	for _, table := range []string{"tcp", "tcp6"} {
		data, err := os.ReadFile(filepath.Join(root, "net", table))
		if err != nil {
			return Held("gateway_listener_unobservable")
		}
		for _, line := range strings.Split(string(data), "\n") {
			fields := strings.Fields(line)
			if len(fields) < 10 || fields[3] != "0A" || !owned[fields[9]] {
				continue
			}
			hexIP, hexPort, ok := strings.Cut(fields[1], ":")
			n, err := strconv.ParseInt(hexPort, 16, 32)
			if ok && err == nil && int(n) == port {
				if procListenerMatches(hexIP, ip) {
					return nil
				}
				// /proc does not expose IPV6_V6ONLY. An owned IPv6 wildcard
				// can serve IPv4 only when exact-inode kernel diagnostics prove
				// that socket's option is disabled; never infer from sysctl.
				if table == "tcp6" && hexIP == strings.Repeat("0", 32) && ip.To4() != nil && dualStackListener(fields[9], port) {
					return nil
				}
			}
		}
	}
	return Held("gateway_listener_mismatch")
}

func procListenerMatches(encoded string, destination net.IP) bool {
	address, err := hex.DecodeString(encoded)
	if err != nil || len(address) != 4 && len(address) != 16 {
		return false
	}
	// Linux /proc net tables encode each 32-bit word in host byte order.
	for i := 0; i < len(address); i += 4 {
		word := binary.NativeEndian.Uint32(address[i : i+4])
		binary.BigEndian.PutUint32(address[i:i+4], word)
	}
	if (destination.To4() != nil) != (len(address) == 4) {
		return false
	} // no guessed dual-stack wildcard semantics
	actual := net.IP(address)
	return actual.Equal(destination) || actual.IsUnspecified()
}
